language: python
python:
- 3.8
services:
- postgresql
install:
- psql -c 'create database django_db owner postgres;' -U postgres
- pip install -r requirements.txt
script:
- python manage.py migrate
- python manage.py test shop/tests/
deploy:
  provider: heroku
  api_key:
    secure: owv7Esbxo+qI577XwYulFhYNtBl7rL6BzUYFbt5j6xdyTV7I4LElTZLpHZ06uNFk7EhZuPO9QqBV0dAEuWx+b3pxnqpnZr2Rxeg8viCcq/0il1iQDVtQ76ORSAhweLIY9qXXXutSPNOMQZv1QK1CA2nWBcHP3ns4w853LbKDxqAZKW5RLHOR5rKYxkHidjz6pCd6minazZrh5iRuw5ym14ObG53nYqzw9t/xARu5npZIGTK2yMmBcgJbSTQxtsBjd2ny5RCXh414BknSItoHkj1qRqLF9klhRtQqsLYkOxjxkhzLZ2Z9ov9qBdzbueSut5oZtgIxDvA2cJYA3Wh10XTA7TVzNB/QlRFXyx0k5HudUW19Per7tJTAgCQik4HlHY+Sz9J5PRUtYHJ3+Exg+Me0cOo7n+m6XZDLXri0gfj7ZLVw0dbrRiSpbznvvyQFAHVMXUy+8sErglwHAvfclqt4kI9Nn6FA+HebVEalVtjtcATzi7xUrsqLO8kesHm3C3Qs3s8Qj6ZtYWHvinNq728/LYAUwCBzfbl+yVdBSO2SIgKzDnxcGXUCGZAr1zr/uXabNEUxUyO+8lYK53ZtbfY62EeEAMGZ2cqMo8A4gZGgExP7HhBoPdOc3NG58AuRekA5sRZYPNNaDrNSURMS3AeBfzxWDG5CoV5zxYZ9veo=
  app: webapp-ivanov-shop
  run: python manage.py loaddata products.yaml && python manage.py migrate
  on: master
